general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    # lock_cmd = playerctl --all-players pause && pidof hyprlock || hyprlock  # pause all system audio and avoid starting multiple hyprlock instances.
    before_sleep_cmd = pidof hyprlock || hyprlock    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
}

# 1. Screensaver
listener {
    timeout = 150                                # 2.5min.
    on-timeout = ~/.config/matrix/scripts/matrix-screensaver.sh start
    on-resume = ~/.config/matrix/scripts/matrix-screensaver.sh stop
}

# 2. Lock
listener {
    timeout = 240                              # 4min  ->  It is actually 240+150, because when screen saver was triggered timer is reset to 0
    on-timeout = pidof hyprlock || hyprlock            # lock screen when timeout has passed
}

# 3. Screen Off (DPMS)
listener {
    timeout = 330                                                    # 5.5min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                            # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}

# 4. Hibernate
listener {
    timeout = 900                                 # 15min
    on-timeout = systemctl hibernate                # suspend pc
}
