-- Generated by nwg-displays on 2026-09-05 at 03:21:27. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1", mode = "1600x1200@60.0",
    position = "1920x0",
    scale = 1,
    vrr = 0
    -- mirror = "eDP-1"
})
-- fallback rule for any mointor
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1,
    mirror = 1
})

